$(function(){
  var currencies = [
   
					{ value: 'abang becak' ,	data: 'adress term for pedicab(s) driver' },
					{ value: 'abu-abu' , 		data: 'grey' },
					{ value: 'ada' , 			data: 'there is/are' },
					{ value: 'adat', data: 'traditional customs' },
					{ value: 'adik' , data:  'sister/brother' },
					{ value: 'afrika selatan', data: 'South africa' },
					{ value: 'agak dekat' , data: 'rather close' },
					{ value: 'agak jauh' , data: 'rather far' },
					{ value: 'agak' , data:  'rather' },
					{ value: 'agama', data:  'religion' },
					{ value: 'agustus' , data:  'august' },
					{ value: 'Air' , data: 'water' },
					{ value: 'akan' , data:  ' will , going to (future marker)' },
					{ value: 'Akrab' , data: 'intimate<' },
					{ value: 'aku' , data: ' i' },
					{ value: 'alam' , data:  'nature, natural '},
					{ value: 'alamat', data: 'address' },
					{ value: 'alat' , data:  'tool' },
					{ value: 'alis' , data:  'eyebrow' },
					{ value: 'ajazair' , data:  'algerian' },
					{ value: 'aman' , data:  'safe' },
					{ value: 'ambil' , data: '(to) take' },
					{ value: 'amerika' , data:  'american' },
					{ value: 'anak' , data:  'child/son/daughter' },
					{ value: 'anda' , data:  'you' },
					{ value: 'anggrek' , data: 'orchid' },
					{ value: 'anggur', data: 'grapes'},
					{ value: 'Angklung', data: 'Suspended bamboo tubes which sounds' },
					{ value: 'Angsa', data:  'swan' },
					{ value: 'anjing' , data:  'dog' },
					{ value: 'Anjungan' , data: 'pavilliun' },				
					{ value: 'antar' , data:  'take' },
					{ value: 'antre' , data:  'to queue'  },					
					{ value: 'apa' , data: 'what' },
					{ value: 'apakah' , data: 'what' },
					{ value: 'apel' , data: 'apple' },
					{ value: 'april', 		data: 'pril' },
					{ value: 'argo', 		data: 'argo (meter)' },		
					{ value: 'arti bearti', data:  '(to) mean' },
					{ value: 'artis', 		data: 'artist' },
					{ value: 'asem' , 		data:  'sour' },
					{ value: 'asin' , data:  'salty' },
					{ value: 'asing', data:  'foreign' },
					{ value: 'asyik', data: 'great' },
					{ value: 'atas', data: 'above' },
					{ value: 'atase', data:  'attache'  },
					{ value: 'australia' , data:  'ausralia' },
					{ value: 'ayah' , data: 'father' },
					{ value: 'ayo cepat' , data:  'hurry up' },
					{ value: 'ayo', data: 'lets(...)come on!!' },
					
					{ value: 'babi', data: 'pig' },
					{ value: 'badak', data: 'rhino(ceros)'},
					{ value: 'bagaimana', data: 'how' },
					{ value: 'bagus juga', data: 'not bad' },
					{ value: 'bagus', data: 'great' },
					{ value: 'bahagia', data: 'happy,cheerful' },					
					{ value: 'bahan', data: 'material' },
					{ value: 'baiklah', data: 'okay' },
					{ value: 'bajaj', data: 'thhree welled bargain-taxi' },
					{ value: 'bajigur', data: 'hot drink made from coconut milk and palm sugar' },
					{ value: 'baju', data: 'shirt,clouse' },					
					{ value: 'bak mandi', data: 'tbath tub' },
					{ value: 'bakau', data: 'mangrove' },
					{ value: 'baki', data: ' tray' },
					{ value: 'bandara (bandar udara)', data: 'airport' },
					{ value: 'bangga', data: 'proud' },
					{ value: 'bangunan', data: 'building' },					
					{ value: 'bank', data: 'bank' },
					{ value: 'bantal', data: 'pillow' },					
					{ value: 'bantu', data: 'to help' },
					{ value: 'bantuan', data: 'help' },
					{ value: 'bapak', data: 'father' },
					{ value: 'barat daya', data: 'south west' },
					{ value: 'barat laut', data: 'north west' },
					{ value: 'barat', data: 'west' },					
					{ value: 'baru', data: 'new' },
					{ value: 'basah', data: 'wet' },
					{ value: 'batak', data: 'batak(in North Sumatera' },
					{ value: 'batik', data: 'batik' },
					{ value: 'batuk', data: 'cough' },					
					{ value: 'bawah', data: 'below' },
					{ value: 'bayam', data: 'spinach' },
					{ value: 'bayar', data: 'to pay' },
					{ value: 'bea cukai', data: 'custom' },
					{ value: 'bebek', data: ' duck' },
					{ value: 'becak', data: 'pedicap, ricksaw' },					
					{ value: 'begitu', data: 'like that' },
					{ value: 'bekerja', data: 'work' },
					{ value: 'bekerja', data: '(to) work' },
					{ value: 'belajar', data: '(to) study' },
					{ value: 'belakang', data: 'back; behind' },
					{ value: 'balalang', data: 'grasshopper' },
					{ value: 'belanda', data: 'dutch' },
					{ value: 'belgia', data: ' belgian' },
					{ value: 'beliau', data: 'he/she' },					
					{ value: 'belimbing', data: 'starfruit' },
					{ value: 'belongsong', data: '(a kind of) wrapper' },
					{ value: 'belum', data: 'not yet' },
					{ value: 'benar', data: 'true, right, correct' },
					{ value: 'benci', data: 'hate' },					
					{ value: 'berada', data: 'to be (at)'},
					{ value: 'beranda', data: 'veranda(h)'},
					{ value: 'berangin', data: 'windy' },
					{ value: 'berangkat', data: '(to) go' },
					{ value: 'berani', data: 'brave' },
					{ value: 'berapa lama', data: 'how long (time)'},
					{ value: 'berapa', data: 'how many/much' },
					{ value: 'berarti', data: '(to) mean' },					
					{ value: 'berat', data: ' heavy' },
					{ value: 'berawan', data: 'cloudy' },
					{ value: 'berbahaya', data: 'dangerous' },
					{ value: 'berbata', data: 'with bricks' },
					{ value: 'berbeda dari', data: 'different from' },
					{ value: 'berdasarkan', data: 'by' },					
					{ value: 'berdiri', data: '(to)stand' },
					{ value: 'bardua', data: 'both of (us)'},
					{ value: 'beres', data: 'no problem' },
					{ value: 'beringin', data: 'banyan' },
					{ value: 'beristirahat', data: '(to) rest' },					
					{ value: 'berjalan', data: '(to) walk' },
					{ value: 'berjemur', data: '(to) sunbathe; (to) dry out under the sun' },					
					{ value: 'berkejaran', data: '(to) run after one another' },
					{ value: 'berkenalan', data: '(be) acquainted' },
					{ value: 'berkunjung', data: ' (to) visit' },
					{ value: 'berlibur', data: '(to be on) vacation' },					
					{ value: 'bermain', data: ' (to) play' },
					{ value: 'bermaksud', data: '(to) intend' },
					{ value: 'bersekolah', data: '(to) go to school' },						
					{ value: 'berselancar', data: '(to) surf' },
					{ value: 'bersih', data: 'clean ' },
					{ value: 'bertani', data: '(to) farm' },
					{ value: 'bertingkat-tingkat', data: 'terrace' },
					{ value: 'berwisata', data: '(to) travel; (to) make a tour' },
					{ value: 'besar', data: 'big' },					
					{ value: 'betapa', data: 'how' },
					{ value: 'betis', data: 'calf' },
					{ value: 'betul', data: 'true, right, correct' },
					{ value: 'biaya', data: 'fee' },
					{ value: 'bibi', data: 'aunt' },					
					{ value: 'bibir', data: 'lips' },
					{ value: 'biodata', data: 'curriculum vitae, resume' },
					{ value: 'biru', data: 'blue' },
					{ value: 'bisa', data: 'can' },
					{ value: 'boleh', data: 'can' },
					{ value: 'bon', data: 'bill' },					
					{ value: 'boneka', data: 'doll' },
					{ value: 'botol', data: 'bottle' },					
					{ value: 'brosur', data: 'brochure' },
					{ value: 'buah', data: 'fruit' },
					{ value: 'buatan', data: 'made of; made in' },
					{ value: 'buaya', data: ' crocodile' },
					{ value: 'budaya', data: ' culture' },
					{ value: 'buka', data: 'open' },					
					{ value: 'bukan', data: ' no; not' },
					{ value: 'bukit', data: 'hill' },
					{ value: 'buku', data: 'book' },
					{ value: 'bulan', data: 'month' },
					{ value: 'bulu mata', data: 'eyelash' },					
					{ value: 'bumbu kacang', data: 'peanut sauce' },
					{ value: 'bunga', data: 'flower' },
					{ value: 'bunga terompet', data: 'morning glory' },
					{ value: 'bungkus', data: 'package;parcel' },
					{ value: 'burung', data: 'bird' },
					{ value: 'burung merak', data: 'peacock' },					
					{ value: 'burung walet', data: 'swallow' },
					{ value: 'bus', data: 'bus' },
					{ value: 'bekerja', data: '(to) work' },
					{ value: 'belajar', data: '(to) study' },
					{ value: 'belakang', data: 'back; behind' },
					{ value: 'balalang', data: 'grasshopper' },
					{ value: 'belanda', data: 'dutch' },
					{ value: 'belgia', data: 'belgian' },
					{ value: 'beliau', data: 'he/she' },					
					{ value: 'belimbing', data: 'starfruit' },
					{ value: 'belongsong', data: '(a kind of) wrapper' },
					{ value: 'belum', data: 'not yet' },
					{ value: 'benar', data: 'true, right, correct' },
					{ value: 'benci', data: 'hate' },					
					{ value: 'berada', data: 'to be (at)'},
					{ value: 'beranda', data: 'veranda(h)'},
					{ value: 'berangin', data: 'windy' },
					{ value: 'berangkat', data: '(to) go' },
					{ value: 'berani', data: 'brave' },
					{ value: 'berapa lama', data: 'how long (time)'},
					{ value: 'berapa', data: 'how many/much' },
					{ value: 'berarti', data: '(to) mean' },					
					{ value: 'berat', data: 'heavy' },
					{ value: 'berawan', data: 'cloudy' },
					{ value: 'berbahaya', data: 'dangerous' },
					{ value: 'berbata', data: ' with bricks' },
					{ value: 'berbeda dari', data: 'different from' },
					{ value: 'berdasarkan', data: 'by' },					
					{ value: 'berdiri', data: '(to)stand' },
					{ value: 'bardua', data: 'both of (us)'},
					{ value: 'beres', data: ' no problem' },
					{ value: 'beringin', data: 'banyan' },
					{ value: 'beristirahat', data: '(to) rest' },					
					{ value: 'berjalan', data: '(to) walk' },
					{ value: 'berjemur', data: '(to) sunbathe; (to) dry out under the sun' },
					{ value: 'bayar', data: 'to pay' },
					{ value: 'bea cukai', data: 'custom' },
					{ value: 'bebek', data: 'duck' },
					{ value: 'becak', data: 'pedicap, ricksaw' },					
					{ value: 'begitu', data: 'like that' },
					{ value: 'bekerja', data: 'work' },
					{ value: 'bekerja', data: '(to) work' },					
					{ value: 'buyut', data: 'great-grandparent' },		
					
					{ value: 'cabai', data: 'chilli' },
					{ value: 'cairan kumur', data: 'mouth wash' },
					{ value: 'calung', data: '(to) bamboo xylophone (Sundanese traditional art)'},
					{ value: 'campak', data: ' meastes' },
					{ value: 'campur', data: 'mix' },
					{ value: 'cangkir', data: 'cup' },
					{ value: 'cantik', data: 'beautiful' },
					{ value: 'catatan', data: 'notes' },
					{ value: 'cecak', data: 'house lizard' },					
					{ value: 'cemara', data: ' pine' },
					{ value: 'cempaka', data: 'tropical magnolia' },
					{ value: 'cempedak', data: 'kind of plant similiar to jackfruit' },
					{ value: 'cendrawasih', data: 'cendrawasih' },
					{ value: 'cepat', data: 'fast' },					
					{ value: 'cerah', data: 'fine, bright' },
					{ value: 'cicit', data: 'great-grandchild' },
					{ value: 'cina', data: 'chinese' },
					{ value: 'cinta', data: 'love' },
					{ value: 'ciri', data: 'charateristic' },
					{ value: 'cokelat', data: 'brown' },					
					{ value: 'cukup dekat', data: 'quite close' },
					{ value: 'cukup jauh', data: 'quite far' },					
					{ value: 'cukup', data: 'enough' },
					{ value: 'cumi-cumi', data: 'squid' },
					
					{ value: 'dada', data: 'chest' },
					{ value: 'daerah', data: 'area;region' },
					{ value: 'daftar harga kamar', data: 'room rate' },
					{ value: 'daftar menu', data: 'menu' },					
					{ value: 'daftar', data: 'list' },
					{ value: 'dagu', data: 'chin' },
					{ value: 'dahi', data: 'forehead' },
					{ value: 'dahlia', data: 'dahlia' },
					{ value: 'dan', data: 'and' },					
					{ value: 'danau', data: 'lake' },
					{ value: 'dandang', data: 'saucepan' },
					{ value: 'dapat, mendapat', data: 'get;obtain' },
					{ value: 'dapur', data: 'kitchen' },
					{ value: 'dari mana', data: '(where)from' },
					{ value: 'dari', data: 'from' },					
					{ value: 'datang', data: 'come' },
					{ value: 'dayak', data: 'dayak (in Kalimantan)'},
					{ value: 'dekat', data: 'close' },
					{ value: 'delapan', data: 'eight' },
					{ value: 'delman', data: 'horse-drawn cart' },
					{ value: 'demam berdarah', data: 'dengue fever' },
					{ value: 'demam', data: 'fever' },
					{ value: 'depan', data: 'front; in front of' },
					{ value: 'dermaga/pelabuhan', data: 'harbour; port(boat)'},
					{ value: 'desa', data: 'village' },
					{ value: 'desember', data: 'december' },
					{ value: 'dewangga', data: 'a kind of cloth design' },
					{ value: 'di atas', data: 'on the top of'},
					{ value: 'di balik', data: 'behind' },					
					{ value: 'di bawah', data: 'below;beneath' },
					{ value: 'di belakang', data: 'back;behind' },
					{ value: 'di depan', data: 'in front of' },
					{ value: 'di kanan', data: 'on the right' },
					{ value: 'di kiri', data: 'on the left' },
					{ value: 'di mana', data: 'where (at)'},
					{ value: 'di pangkal', data: ' at the beginning' },
					{ value: 'di samping', data: 'beside ' },					
					{ value: 'di sana/ di situ', data: 'there' },
					{ value: 'di sebelah', data: 'next to' },
					{ value: 'di sini', data: 'here (refers to a place near the speaker' },
					{ value: 'di situ', data: 'there (refers to a place close to the listener)'},
					{ value: 'di tengah', data: ' in the middle of' },
					{ value: 'di ujung', data: 'at the end' },					
					{ value: 'di', data: 'at;in;on' },
					{ value: 'dia', data: 'he/she' },
					{ value: 'diangkat', data: '(to) lift up' },
					{ value: 'dibangun', data: '(be) built' },
					{ value: 'digunakan', data: '(to be ) used' },					
					{ value: 'diisi', data: '(to be) filled' },
					{ value: 'dikaitkan dengan(be) related to' },					
					{ value: 'dinding ', data: 'wall' },
					{ value: 'dingin', data: '(be) cold' },
					{ value: 'dipentaskan', data: '(be) performanced' },
					{ value: 'dokar', data: 'horse-drawn cart' },					
					{ value: 'dokter gigi', data: 'dentist' },					
					{ value: 'dokter', data: 'Doctor(to) intend' },
					{ value: 'dolar', data: 'dollar' },						
					{ value: 'dompet', data: 'wallet' },
					{ value: 'dosen', data: 'lecturer' },
					{ value: 'dua belas', data: 'twelve' },
					{ value: 'dua puluh', data: 'twenty' },
					{ value: 'dua ratus', data: 'two hundred' },
					{ value: 'dua ribu', data: 'two thousand' },					
					{ value: 'dua', data: 'two' },
					{ value: 'duduk', data: '(to)sit' },
					{ value: 'dulu', data: '(at) first' },
					{ value: 'durian', data: 'durian;duren' },
					{ value: 'duta besar', data: 'ambassador' },	
					
					{ value: 'elang' , data:  'eagle' },
					{ value: 'ember' , data:  'pail (bucket)'},
					{ value: 'empat' , data:  'four' },
					{ value: 'enak' , data:  'delicious, nice' },
					{ value: 'enam' , data:  'six' },
					{ value: 'es cendol' , data:  'small doughly rice-flour droplets served with ice and thin coconut milk' },					
					{ value: 'es dawet' , data:  '(iced "drink"; more or less the same as cendol)'},
					{ value: 'es kelapa muda' , data:  'green coconut meat mixed with its juice and served with ice'},
					{ value: 'eskalator' , data:  ' escalator' },
					
					{ value: 'februari', data: 'february' },
					{ value: 'flu', data: 'cold' },
					{ value: 'formulir', data: 'form' },
					{ value: 'gado-gado', data: 'a kind of salad-sliced potato, cucumber, vegetables,"tempe", and tofu,etc. mixed with a spicy peanut sauce' },
					{ value: 'gamelan', data: 'brass percussion orchestra' },					
					{ value: 'garasi', data: 'garage' },
					{ value: 'garpu', data: 'fork' },
					{ value: 'garuda', data:  'eagle (Indonesia(s) national symbol)'},
					{ value: 'gayung', data: 'dipper' },
					{ value: 'gelap', data: 'dark' },					
					{ value: 'gelas', data: 'glass' },
					{ value: 'gembira', data: 'happy,pleased' },
					{ value: 'gemuk', data: 'fat' },
					{ value: 'gemulai', data: 'supple,pliant' },
					{ value: 'gerai', data: ' a small stand/stall; counter' },
					{ value: 'gerakan', data: 'movement' },					
					{ value: 'gereja', data: 'chruch' },
					{ value: 'golongan darah', data: 'blood type' },
					{ value: 'gudang', data: 'shed' },
					{ value: 'guling', data: 'bolster' },
					{ value: 'gunung', data: 'mountain' },
					{ value: 'gurih', data: 'delicious' },
					{ value: 'gurita', data: 'octopus' },
					{ value: 'guru', data: 'teacher' },
					
					{ value: 'habis,slesai', data: '(to) finish' },					
					{ value: 'halaman', data: 'yard' },
					{ value: 'halte (bus)', data: 'bus stop' },
					{ value: 'hampir', data: 'almost' },
					{ value: 'handuk', data: 'towel' },
					{ value: 'harga', data: 'price' },					
					{ value: 'hari ini', data: 'today ' },
					{ value: 'hari', data: 'day' },
					{ value: 'harimau', data: 'tiger' },
					{ value: 'harum', data: 'fragant' },
					{ value: 'harus', data: 'must;have to' },
					{ value: 'hati-hati', data: '(to be) careful' },					
					{ value: 'hendak', data: 'will; (to) be going to' },
					{ value: 'hidung', data: 'nose' },					
					{ value: 'hijau', data: 'green' },
					{ value: 'hilang', data: 'lost' },
					{ value: 'hindu', data: 'hindu' },
					{ value: 'hitam', data: 'black' },
					{ value: 'hitung', data: 'count' },
					{ value: 'hotel', data: 'hotel' },					
					{ value: 'hujan', data: 'rain,rainy' },
					
					{ value: 'ia', data: 'he/she' },
					{ value: 'ibu kota', data: 'capital city' },
					{ value: 'ibu', data: 'mother' },
					{ value: 'identitas', data: 'identity' },					
					{ value: 'ikan', data: 'fish' },
					{ value: 'ikan emas', data: 'goldfish' },
					{ value: 'imigrasi', data: 'immigration' },
					{ value: 'indah', data: 'beautiful' },
					{ value: 'Indonesia', data: 'indonesian' },
					{ value: 'informasi', data: 'information' },					
					{ value: 'inggris', data: 'English' },
					{ value: 'ingin', data: '(to) want' },
					{ value: 'ini', data: 'this/these(refers to something that is close to the speaker)'},
					{ value: 'internet', data: 'internet' },								
					{ value: 'isi', data: '(to) fill' },
					{ value: 'istimewa', data: 'special' },
					{ value: 'istirahat', data: ' (to) rest' },
					{ value: 'istri', data: 'wife' },					
					{ value: 'italia', data: 'italian' },
					{ value: 'itu', data: 'that/those (refers to something that is close to the listener)'},
					{ value: 'indah', data: 'beautiful' },
					{ value: 'Indonesia', data: 'Indonesia' },
					{ value: 'informasi', data: 'information' },					
					{ value: 'inggris', data: 'English,England' },
													
					{ value: 'jalan', data: 'street,road' },
					{ value: 'jalan-jalan', data: 'sightseeing' },
					{ value: 'jalur', data: 'line' },
					{ value: 'jambu biji', data: 'guava' },
					{ value: 'jamburose-apple( kind of fruit)'},
					{ value: 'januari', data: 'january' },					
					{ value: 'jati', data: 'teak (wood)'},
					{ value: 'jauh', data: 'far' },
					{ value: 'jawa', data: 'javanese ( in central and east Java)'},
					{ value: 'Jenis kelamin', data: 'sex' },
					{ value: 'jenis', data: 'type' },					
					{ value: 'jepang', data: 'japanese' },
					{ value: 'jerman', data: 'german' },
					{ value: 'jeruk', data: 'orange' },
					{ value: 'jingga', data: 'orange' },
					{ value: 'juga', data: 'also' },
					{ value: 'juli', data: 'july' },					
					{ value: 'jumat', data: 'friday' },
					{ value: 'jumpa lagi', data: 'see you again' },					
					{ value: 'juni', data: 'juni' },
					{ value: 'jus jeruk', data: 'orange juice' },
					{ value: 'jus mangga', data: 'mango juice' },					
					
					{ value: 'kacang panjang', data: 'long bean' },
					{ value: 'kafe', data: 'cafe' },
					{ value: 'kain', data: 'cloth' },					
					{ value: 'kakak', data: 'elder brother/sister' },
					{ value: 'kakek', data: 'grandfather' },
					{ value: 'kaki', data: 'leg' },
					{ value: 'kalau', data: 'if;when' },
					{ value: 'kalian', data: 'you(all)' },			
					{ value: 'kamar', data: 'room' },
					{ value: 'kamar mandi', data: 'bathroom' },
					{ value: 'kamar standar', data: 'standard room' },
					{ value: 'kamboja', data: 'frangipani' },
					{ value: 'kamera', data: 'camera' },
					{ value: 'kami', data: 'we;our' },					
					{ value: 'kamis', data: 'thursday' },				
					{ value: 'kamu', data: 'you' },
					{ value: 'kanada', data: 'canada' },
					{ value: 'kanan', data: 'right' },
					{ value: 'kangkung', data: 'water convovulus' },
					{ value: 'kantin', data: 'canteen' },
					{ value: 'kantong plastik', data: 'plastic bag' },
					{ value: 'kantor pos', data: 'post office' },
					{ value: 'kantor', data: 'office' },						
					{ value: 'kapal laut', data: 'ship' },
					{ value: 'kapan', data: 'when' },
					{ value: 'kartu identitas', data: 'identity card' },
					{ value: 'kartu kredit', data: 'credit card' },
					{ value: 'kartu nama', data: 'name card' },					
					{ value: 'karya', data: 'work' },
					{ value: 'karyawan', data: 'employee)'}, 
					{ value: 'kasir', data: 'cashier' },
					{ value: 'katun', data: 'cotton' },
					{ value: 'kau', data: 'you' },
					{ value: 'kawan', data: 'friend' },					
					{ value: 'kayu', data: 'wood' },
					{ value: 'ke mana', data: 'where (to)' },					
					{ value: 'ke', data: 'to' },
					{ value: 'kebaikan', data: 'kindness' },
					{ value: 'kebetulan', data: 'by chance;accidentally' },
					{ value: 'kebun', data: 'garden' },
					{ value: 'kecapi', data: 'kind of sour' },
					{ value: 'kecewa', data: 'dissapointed' },					
					{ value: 'kecil', data: 'small' },
					{ value: 'kedai', data: 'small shop (that sells something or serving food)'},
					{ value: 'kedondong', data: 'kind of sour; plumlike fruit' },
					{ value: 'kedua', data: 'second' },
					{ value: 'kedutaan', data: 'embassy' },					
					{ value: 'keindahan', data: 'beauty' },
					{ value: 'kelahiran', data: 'birth' },					
					{ value: 'kelelawar', data: 'bat' },
					{ value: 'keliling', data: 'travel around' },
					{ value: 'keluarga', data: 'family' },
					{ value: 'kemakmuran', data: 'prosperity' },					
					{ value: 'kemarau', data: 'dry (season)' },
					{ value: 'kemarin', data: 'yesterday' },
					{ value: 'kembali', data: '(to) go back; (to) return' },						
					{ value: 'kembang sepatu', data: 'hibiscus' },
					{ value: 'kemudian', data: 'then ' },
					{ value: 'kenal', data: '(to) know' },
					{ value: 'kenalkan', data: 'allow me to introduce (..)'},
					{ value: 'kepala kerbau', data: 'buffalo(s) head' },
					{ value: 'keperluan', data: 'need,necessity' },					
					{ value: 'kera', data: 'monkey' },
					{ value: 'kerajinan tangan', data: 'handy craft' },
					{ value: 'keranjang', data: 'basket' },
					{ value: 'kereta api', data: 'train' },
					{ value: 'kering', data: 'dry' },					
					{ value: 'kerja keras', data: 'hard work' },
					{ value: 'kesehatan', data: 'health' },
					{ value: 'keseleo', data: 'sprain' },
					{ value: 'ketiak', data: 'ampit' },
					{ value: 'ketiga', data: 'third' },
					{ value: 'ketoprak (makanan)', data: 'Jakarta special food : rice cooked in banana leaf,fried tofu,bean sprouts,etc. covered with soya and peanut sauce' },
					{ value: 'ketoprak (seni)', data: 'Javanese traditional art' },
					{ value: 'kewarganegaraan', data: 'nationality' },					
					{ value: 'khas', data: 'unique' },
					{ value: 'khusus', data: 'special' },
					{ value: 'kijang/rusa', data: 'deer' },
					{ value: 'kilogram', data: 'kilogram' },
					{ value: 'kios', data: 'kiosk' },
					{ value: 'kira-kira', data: 'about;estimately' },					
					{ value: 'kiri', data: 'left' },
					{ value: 'kita', data: 'we;our' },
					{ value: 'Keterangan izin tinggal sementara(KITAS)', data: 'temporary stay permit' },
					{ value: 'kok', data: 'wow (expression of surprise)'},
					{ value: 'koki', data: 'chef' },					
					{ value: 'kokoh', data: 'strong' },
					{ value: 'kolam renang', data: 'swimming pool' },					 
					{ value: 'Kolintang', data: 'minahasa musical instrument' },
					{ value: 'komodo', data: 'komodo' },
					{ value: 'kompor', data: 'stove' },
					{ value: 'komputer', data: 'computer' },					
					{ value: 'konsulat jenderal', data: 'consulate general' },
					{ value: 'koper', data: 'suitvase,luggage , trunk' },
					{ value: 'kosong', data: 'empty' },
					{ value: 'kota', data: 'town;city' },
					{ value: 'KTP (kartu tanda Penduduk)', data: 'citizen identity card' },
					{ value: 'kubis', data: 'cabagge' },
					{ value: 'kucing', data: 'cat' },
					{ value: 'kuda lumping', data: 'javanese traditionl art' },
					{ value: 'kuil', data: 'temple or shrine used by indian Hindus' },					
					{ value: 'kunci', data: 'key' },
					{ value: 'kunjungan', data: 'visit' },
					{ value: 'kunjungi', data: 'to visit' },
					{ value: 'kupu-kupu', data: 'butterfly' },
					
					
					{ value: 'laba-laba', data: 'Spider' },					
					{ value: 'lain', data: 'other(s)' },
					{ value: 'lalat', data: 'fly' },
					{ value: 'lalu', data: 'then'},
					{ value: 'lama', data: 'long time' },
					{ value: 'lambat', data: 'slow' },
					{ value: 'langsung', data: 'directly' },					
					{ value: 'lapor masuk', data: 'check-in' },
					{ value: 'laut lepas', data: 'ocean' },					
					{ value: 'laut', data: 'sea' },
					{ value: 'lebah', data: 'bee' },
					{ value: 'lebih lama', data: 'longer' },
					{ value: 'lebih suka', data: 'to prefer' },
					{ value: 'legen', data: 'sugar palm milk' },
					{ value: 'leher', data: 'neck' },					
					{ value: 'lele', data: 'catfish' },
					{ value: 'lemari es', data: 'refrigerator' },
					{ value: 'lembayung', data: 'violet' },
					{ value: 'lembut', data: 'soft' },
					{ value: 'lengan', data: 'arm' },					
					{ value: 'lengan atas', data: 'upper arm' },
					{ value: 'lengan bawah', data: 'lower arm' },
					{ value: 'lezat', data: 'delicious;tasty' },
					{ value: 'libur', data: 'vacation' },
					{ value: 'liburan', data: 'holiday' },
					{ value: 'lihat', data: '(to) see, (to) look)'},					
					{ value: 'lima', data: 'five' },
					{ value: 'lincah', data: 'lively,agile' },
					{ value: 'lobak', data: 'radish' },					
					{ value: 'lorong', data: 'passageway' },							
					{ value: 'losmen', data: 'inn' },
					{ value: 'loteng', data: 'attic' },
					{ value: 'luar biasa', data: 'extraordinary;amazing' },
					{ value: 'luas', data: 'large;broad' },
					{ value: 'lucu', data: 'funny' },
					{ value: 'luka', data: 'wound' },					
					{ value: 'lukisan', data: 'painting' },
					{ value: 'luntur', data: 'to ruin out' },
					{ value: 'lutut', data: 'knee' },
					
					{ value: 'maaf', data: 'excuse me, sorry' },
					{ value: 'madura', data: 'madura( a small island of java)' },				
					{ value: 'mahal', data: ' expensive' },
					{ value: 'mahasiswa', data: 'university student' },
					{ value: 'makan', data: '(to) eat' },
					{ value: 'makan malam', data: 'dinner' },
					{ value: 'makan siang', data: 'lunch' },
					{ value: 'malaria', data: 'malaria' },					
					{ value: 'malu', data: 'embarassed' },
					{ value: 'mamalia', data: 'mammale' },					
					{ value: 'mampir (informal)', data: '(to) stay; (to) visit a short time' },
					{ value: 'mancanegara', data: 'foreign country' },
					{ value: 'mandi', data: '(to) take a bath' },
					{ value: 'mangga', data: 'manggo' },
					{ value: 'manggis', data: 'mangosteen' },
					{ value: 'mangkuk', data: 'bowl' },					
					{ value: 'manis', data: 'sweet' },
					{ value: 'maret', data: '>march' },
					{ value: 'mari', data: 'lets (...), come on' },
					{ value: 'masakan ', data: 'food' },
					{ value: 'masakan Indonesia', data: 'Indonesian food' },					
					{ value: 'masakan khas', data: 'special food' },
					{ value: 'masih', data: '<i>still' },
					{ value: 'masjid', data: 'mosque' },
					{ value: 'masuk angin', data: 'catch a cold' },
					{ value: 'masyarakat', data: 'society' },
					{ value: 'masing-masing', data: 'each, every' },					
					{ value: 'mata kaki', data: 'ankle' },
					{ value: 'mata', data: 'eyes' },
					{ value: 'matahari', data: 'sun flower' },
					{ value: 'matang', data: 'ripe' },
					{ value: 'mawar', data: ' rose' },
					{ value: 'medium', data: 'medium' },
					{ value: 'megah', data: 'luxurious' },
					{ value: 'mei', data: ' mei' },
					{ value: 'meja', data: 'table' },					
					{ value: 'melambangkan', data: '(to) simbolize' },
					{ value: 'melapor', data: '(to) report' },
					{ value: 'melati', data: 'jasmine' },
					{ value: 'melon<', data: 'melon' },
					{ value: 'memakai', data: '(to) wear' },					
					{ value: 'memasak', data: '(to) cook' },
					{ value: 'membaca', data: '(to) read' },
					{ value: 'membantu', data: '(to) help' },
					{ value: 'membawa', data: '(to) bring; (to) take' },
					{ value: 'membayar', data: '(to) pay' },
					{ value: 'memberi', data: '(to) give' },					
					{ value: 'memriksa', data: '(to) check' },
					{ value: 'memiliki', data: '(to) have ' },					
					{ value: 'meminta', data: '(to) ask' },
					{ value: 'memotret', data: '(to) take a picture' },
					{ value: 'mempunyai', data: '(to) have' },
					{ value: 'menantu', data: 'daughter/son in law' },
					{ value: 'menarik sekali', data: 'very interesting' },
					{ value: 'mencari', data: '(to) look for' },	
					{ value: 'merdu', data: 'mellodius' },
					{ value: 'mereka', data: 'they' },
					{ value: 'merpati', data: 'pigeon;dove' },
					{ value: 'mertua', data: 'mother/father in law' },
					{ value: 'mesir', data: 'egyptian' },
					{ value: 'mikrolet', data: 'public station-wagon "mini bus" ' },
					{ value: 'milik siapa', data: 'whose' },
					{ value: 'minahasa', data: 'minahasa (in sulawesi)' },			
					{ value: 'minang', data: 'minangkabau (In central sumatera)' },
					{ value: 'minggu', data: 'sunday' },
					{ value: 'minum', data: '(to) drink' },
					{ value: 'minuman', data: 'drink' },
					{ value: 'mobil', data: 'car' },
					{ value: 'mode', data: 'model' },					
					{ value: 'moksa', data: 'redemption' },
					{ value: 'motel', data: 'motel' },
					{ value: 'motif', data: 'motive' },
					{ value: 'mujair', data: 'fresh water fish' },
					{ value: 'mulut', data: 'mouth' },					
					{ value: 'musim', data: 'season' },
					{ value: 'mencuci', data: '(to) wash' },
					{ value: 'mendung', data: 'overcast' },
					{ value: 'menerima', data: '(to) receive; accept' },
					{ value: 'mengagumi', data: '(to) admire' },
					{ value: 'mengantar', data: '(to) take someone' },					
					{ value: 'mengantarkan', data: '(to) accompany; (to) bring' },
					{ value: 'mengapa', data: 'why' },					
					{ value: 'menghampiri', data: '(to) take someone' },
					{ value: 'menginap', data: '(to) spend the night;(to) stay' },
					{ value: 'mengirim', data: '(to) send' },
					{ value: 'mengiringi', data: '(to) go along with' },					
					{ value: 'mengisi', data: '(to) fill' },
					{ value: 'mengkudu', data: 'morinda' },
					{ value: 'mengundang', data: '(to) invite' },						
					{ value: 'mengurus', data: '(to) arrange; (to) manage' },
					{ value: 'menikmati', data: '(to) enjoy ' },
					{ value: 'menonton', data: '(to) see' },
					{ value: 'menu', data: 'dish (type of foos served' },
					{ value: 'menyapa', data: '(to) greet; address someone' },
					{ value: 'menyapu', data: '(to) sweep ' },					
					{ value: 'menyediakan', data: 'provide' },
					{ value: 'menyesal', data: 'regret' },
					{ value: 'menyewa', data: '(to) hire, (to) rent' },
					{ value: 'merah muda', data: 'pink' },
					{ value: 'merah', data: 'red' },	
					
					{ value: 'naik', data: '(to) go u[; (to) travel (by vehicle)' },
					{ value: 'nama', data: ' name' },
					{ value: 'nangka', data: 'jackfruit' },
					{ value: 'nanti', data: 'later' },
					{ value: 'nasi goreng', data: 'fried rice' },					
					{ value: 'nasi gudeg', data: 'a speacial food yogyakarta: young jackfruit cooked with coconut milk and served with warm rice' },
					{ value: 'nasi', data: 'rice' },
					{ value: 'negara', data: 'country' },
					{ value: 'nenek', data: 'grandmother' },
					{ value: ' nona', data: 'miss' },
					{ value: 'november', data: 'november' },
					{ value: 'nyaman', data: 'comfortable' },
					{ value: 'nyamuk', data: ' mosquito' },
					{ value: 'nyonya', data: 'Mrs. (not neccessarily with surname)' },
					
					{ value: 'ojek', data: 'bicycle/motorcycle "taxi" ' } ,
					{ value: 'oktober', data: 'oktober' },
					{ value: 'olah raga', data: '(to) exercise' },
					{ value: 'ombak', data: 'wave' },
					{ value: 'omong-omong', data: 'by the way' },					
					{ value: 'orang', data: 'person , people' },
					
					{ value: 'pada prinsipnya', data: 'basically' },
					{ value: 'padi', data: 'paddy' },
					{ value: 'pagi', data: 'morning' },
					{ value: 'paha', data: 'thigh' },
					{ value: 'pahit', data: 'bitter' },					
					{ value: 'pakai', data: '(to) use' },
					{ value: 'paman', data: 'uncle' },					
					{ value: 'panas', data: 'hot' },
					{ value: 'panci', data: 'pan' },
					{ value: 'panggil', data: '(to) call' },
					{ value: 'pangkalan', data: 'taxi stand' },
					{ value: 'panjang', data: 'long' },
					{ value: 'pantai', data: 'beach' },					
					{ value: 'pantas saja', data: 'no wonder' },
					{ value: 'pari', data: 'rayfish' },
					{ value: 'pas', data: 'fixed' },
					{ value: 'pasar swalayan', data: 'super market' },
					{ value: 'pasar', data: 'market' },					
					{ value: 'pasaraya', data: 'hipermarket' },
					{ value: 'pasir', data: 'sand' },
					{ value: 'paspor', data: 'pasport' },
					{ value: 'pasta gigi', data: 'toothpaste' },
					{ value: 'pasti', data: 'sure' },
					{ value: 'patung', data: 'statue' },					
					{ value: 'pekalongan', data: 'a town in central java' },
					{ value: 'pekan', data: 'week' },
					{ value: 'pelayan kamar', data: 'room boy' },					
					{ value: 'pelayan hotel', data: 'room attendant' },
					{ value: 'pelayan', data: 'waiter;waitress' },					
					{ value: 'pemandu', data: 'guide' },
					{ value: 'pemandangan', data: 'view<i>' },
					{ value: 'pembayaran', data: 'payment<i>' },
					{ value: 'pemujaan', data: 'worship' },
					{ value: 'penari', data: 'dancer' },
					{ value: 'pendek', data: 'short' },					
					{ value: 'penduduk', data: 'inhabitant;villagers' },
					{ value: 'peneliti', data: 'researcher' },					
					{ value: 'penginapan', data: 'overnights lodging' },
					{ value: 'pengusaha', data: 'entrepreneur' },
					{ value: 'penjual', data: 'seller;vendor' },
					{ value: 'penjualan', data: 'sale' },
					{ value: 'penuh', data: 'full' },
					{ value: 'penulis', data: 'writer' },					
					{ value: 'penumpang', data: 'passeger' },
					{ value: 'penyanyi', data: 'singer' },
					{ value: 'pepaya', data: 'paw-paw;papaya' },
					{ value: 'perahu', data: 'canoe;boat' },
					{ value: 'perempatan', data: 'square' },					
					{ value: 'pergelangan tangan', data: 'wrist' },
					{ value: 'periksa', data: 'check' },
					{ value: 'pernah', data: 'ever' },
					{ value: 'pertama', data: 'first' },
					{ value: 'pertunjukan', data: 'performance' },
					{ value: 'perut', data: 'stomach' },					
					{ value: 'pesan', data: '(to) order; message' },
					{ value: 'pesawat terbang', data: 'aeroplane(us: airplane)' },
					{ value: 'petak', data: 'a portion of field' },					
					{ value: 'petani', data: 'farmer' },							
					{ value: 'petugas', data: 'officer, attendant' },
					{ value: 'pilek', data: 'cold' },
					{ value: 'pilih', data: '(to) choose' },
					{ value: 'pilot', data: 'pilot' },
					{ value: 'pinggang', data: 'waist' },
					{ value: 'pipi', data: 'cheek' },					
					{ value: 'pir', data: 'pear' },
					{ value: 'piring', data: 'plate' },
					{ value: 'pisang', data: 'banana' },
					{ value: 'pisau', data: 'kinfe' },
					{ value: 'pohon', data: 'tree' },					
					{ value: 'polisi', data: 'police' },
					{ value: 'pompa bensin', data: 'gas station' },
					{ value: 'ponsel', data: 'hand phone; cell phone; mobile phone' },
					{ value: 'pramugara', data: '(air) steward' },
					{ value: 'pramugari', data: '(air) stewardess' },
					{ value: 'pramuniaga', data: 'sales assistant' },					
					{ value: 'prancis', data: 'french' },
					{ value: 'prei (informal)', data: 'vacation' },					
					{ value: 'puas', data: 'satisfy' },
					{ value: 'pucuk pohon', data: 'top of tree' },
					{ value: 'pulang', data: 'go home;return' },
					{ value: 'pulau', data: 'island' },
					{ value: 'pura', data: 'Balinese temple; shrine' },
					{ value: 'puri', data: 'palace' },					
					{ value: 'pusat kebudayaan', data: 'culture centre(US : center) ' },
					{ value: 'puskesmas', data: 'community health centre' },
					{ value: 'putih', data: 'white' },
					{ value: 'putra', data: 'son' },
					{ value: 'putri', data: 'daughter' },
					
					{ value: 'rabu', data: 'wednesday' },
					{ value: 'radio', data: 'radio' },
					{ value: 'raja', data: 'king' },
					{ value: 'ramai', data: 'crowded;busy' },
					{ value: 'rambut', data: 'hair' },
					{ value: 'rambutan', data: 'rambutan (similiar to lychee)'},				
					{ value: 'ransel', data: 'rucksack/backpack' },
					{ value: 'rendah', data: 'low' },
					{ value: 'reog', data: '(javanese) masked dance;(sundanese) singing comedy group' },
					{ value: 'reptil', data: 'reptile' },
					{ value: 'resepsionis', data: 'receptionist' },
					{ value: 'restoran', data: 'restaurant' },
					{ value: 'rindu', data: 'longing; miss' },					
					{ value: 'ruang keluarga', data: 'sitting room' },
					{ value: 'ruang makan</strong>', data: 'dinning room' },					
					{ value: 'ruang tamu', data: 'living room' },
					{ value: 'ruang tidur', data: 'bed room' },
					{ value: 'rumah adat', data: 'traditional house' },
					{ value: 'rumah makan', data: 'restaurant' },
					{ value: 'rumah sakit', data: 'hospital' },					
					{ value: 'rumah', data: 'house' },
					{ value: 'rupiah', data: 'rupiah' },
					
					{ value: 'sabar', data: 'patient' },
					{ value: 'sabtu', data: 'saturday' },
					{ value: 'sabun', data: 'soap' },
					{ value: 'sadar', data: '(to) realize' },					
					{ value: 'saja', data: 'just;only' },
					{ value: 'sakit kepala<', data: 'headache ' },					
					{ value: 'sakit mata', data: 'sore eyes' },
					{ value: 'sakit perut', data: 'stomachache' },
					{ value: 'sakit', data: 'sick' },
					{ value: 'saku,kantong', data: 'poket' },
					{ value: 'salah', data: 'wrong;false' },
					{ value: 'salem', data: 'salmon' },					
					{ value: 'sama dengan', data: 'similiar (to)' },
					{ value: 'sambil', data: 'while' },
					{ value: 'sampai', data: '(to) arriveve' },
					{ value: 'samping', data: 'beside' },
					{ value: 'sampo', data: 'shampoo' },					
					{ value: 'sana', data: 'that/those (refers to something daf from the speaker and the listener)' },
					{ value: 'sangat dekat', data: 'very near;close' },					
					{ value: 'sangat jauh', data: 'very far' },
					{ value: 'sanggah', data: 'family temple' },
					{ value: 'santan', data: 'coconut milk' },
					{ value: 'sapi', data: 'cow' },					
					{ value: 'sarapan', data: 'breakfast' },
					{ value: 'sariawan', data: 'sorelips' },
					{ value: 'sarung', data: 'sarong' },						
					{ value: 'sate', data: '(to) arrange; (to) manage' },
					{ value: 'satpam', data: '(to) seurity guard ' },
					{ value: 'satu per satu', data: 'one by one' },
					{ value: 'satu', data: 'one' },
					{ value: 'sawah', data: 'rice field' },
					{ value: 'sawo', data: 'sapodilla ' },					
					{ value: 'saya', data: 'i ; me' },
					{ value: 'sayuran', data: 'vegetables' },
					{ value: 'sebelah', data: 'side' },
					{ value: 'sebelas', data: 'eleven' },
					{ value: 'sebentar', data: 'just a moment' },					
					{ value: 'sebetulnya, sebenarnya', data: 'in fact; actually' },
					{ value: 'sebuah', data: 'a (a  noun classifier)' },
					{ value: 'sederhana', data: 'simple' },
					{ value: 'sedia', data: 'available' },
					{ value: 'sedih', data: 'sad' },
					{ value: 'segera', data: 'soon; immediately' },					
					{ value: 'sejarah', data: 'history' },
					{ value: 'sejuk sekali', data: 'very cool' },					
					{ value: 'sejuk', data: ' cool' },
					{ value: 'sekarang', data: 'now; right now' },
					{ value: 'sekolah', data: 'school' },
					{ value: 'sekoteng', data: 'hot giner tea added with slice bread, nuts.etc' },
					{ value: 'selada', data: 'lettuce' },
					{ value: 'selamat', data: 'safe; congratulation' },					
					{ value: 'selamat berjumpa', data: 'nice to meet you' },
					{ value: 'selamat bertemu lagi', data: 'nice to see you again' },
					{ value: 'selamat datang', data: 'welcome' },
					{ value: 'selamat jalan', data: 'good bye' },
					{ value: 'selamat malam', data: 'good evening' },					
					{ value: 'selamat pagi', data: 'good morning' },
					{ value: 'selamat siang', data: 'good day' },
					{ value: 'selamat sore', data: 'good afternoon' },					
					{ value: 'selamat tinggal ', data: 'good bye' },					
					{ value: 'selasa', data: 'tuesday' },
					{ value: 'selat', data: 'strait' },
					{ value: 'selatan', data: 'south' },
					{ value: 'selera', data: 'appetite' },
					{ value: 'selimut', data: 'blanket' },					
					{ value: 'semangka', data: 'watermelon' },
					{ value: 'sembilan', data: 'nine' },
					{ value: 'semoga', data: 'i hope' },
					{ value: 'sempit', data: 'narrow' },
					{ value: 'semua', data: 'all' },
					{ value: 'senang', data: 'happy;pleased;glad' },					
					{ value: 'sendirian', data: 'alone' },
					{ value: 'sendok', data: 'spoon' },					
					{ value: 'seni', data: 'art' },
					{ value: 'senin', data: 'monday' },
					{ value: 'sepanjang', data: 'along' },
					{ value: 'sepeda motor', data: 'motorcycle' },
					{ value: 'sepeda', data: 'bicycle' },
					
					{ value: 'sepi', data: 'quiet' },					
					{ value: 'seprai', data: 'bedsheet' },
					{ value: 'september', data: 'september' },
					{ value: 'sepuluh', data: 'ten' },
					{ value: 'sepupu', data: 'cousin' },
					{ value: 'serahkan', data: '(to) give' },					
					{ value: 'serangga', data: 'insect' },
					{ value: 'seratus', data: 'one hundred' },
					{ value: 'seribu', data: 'one thousand' },
					{ value: 'sering', data: 'often' },
					{ value: 'setelah', data: 'afer' },
					{ value: 'setuju', data: '(to) agree' },					
					{ value: 'sewa', data: '(to) rent; (to) hire' },
					{ value: 'siapa', data: 'who' },
					{ value: 'sikat gigi', data: 'tooth brush' },					
					{ value: 'sikat', data: 'brush' },
					{ value: 'siku', data: 'elbow' },					
					{ value: 'silakan', data: 'please' },
					{ value: 'silakan duduk', data: 'please sit down' },
					{ value: 'silakan masuk', data: 'please come in' },
					{ value: 'SIM (surat ijin mengemudi', data: 'driver(s) license' },
					{ value: 'singa', data: 'lion' },
					{ value: 'singgah', data: '(to) stay ; (to) visit a short time' },					
					{ value: 'sirsak', data: 'soursop (kind of fruit)' },
					{ value: 'sistem', data: 'system' },					
					{ value: 'solo', data: 'town in a Central java' },
					{ value: 'sopir', data: 'driver' },
					{ value: 'soto', data: 'soup cooked with hot water or coconut milk' },
					{ value: 'stasiun', data: 'train station' },
					{ value: 'spanyol', data: 'Spanish' },
					{ value: 'status perkawinan', data: 'Marrieage status' },					
					{ value: 'stroberi', data: 'strawberry' },
					{ value: 'suami', data: 'husband' },
					{ value: 'suara', data: 'sound' },
					{ value: 'sudah', data: 'already (also past time marker)' },
					{ value: 'suka<', data: 'like' },					
					{ value: 'suku', data: 'tribe' },
					{ value: 'suling', data: 'bamboo flute' },
					{ value: 'sungai', data: '<i>river' },
					{ value: 'supermarket', data: 'supermarket' },
					{ value: 'susu kedelai', data: 'soybean milk' },
					{ value: 'sutra', data: 'silk' },					
					{ value: 'syukur', data: 'thank god' },
					
					
					{ value: 'tahu, mengetahui', data: '(to) know' },
					{ value: 'tahun', data: 'year' },					
					{ value: 'taksi', data: 'taxi' },							
					{ value: 'tanah', data: 'soil' },
					{ value: 'tanda pengenal', data: 'identity card' },
					{ value: 'tanda tangan', data: 'signature' },
					{ value: 'tangan', data: 'hand' },
					{ value: 'tanggal', data: 'date' },
					{ value: 'tanjung', data: 'cape' },					
					{ value: 'tari penyambutan', data: 'welcoming dance' },
					{ value: 'tari', data: 'dance' },
					{ value: 'tarian', data: 'dance' },
					{ value: 'tas', data: 'bag' },
					{ value: 'tas kresek', data: 'plastic bag' },					
					{ value: 'tebing', data: 'cliff' },
					{ value: 'teh', data: 'tea' },
					{ value: 'teko', data: 'teapot' },
					{ value: 'telapak kaki', data: 'foot' },
					{ value: 'telepon genggam', data: 'handphone; cell phone (US) mobile phone,phone (Australia)' },
					{ value: 'telepon', data: 'telephone' },					
					{ value: 'televisi', data: 'television' },
					{ value: 'telinga', data: 'ear' },					
					{ value: 'teluk', data: 'bay' },
					{ value: 'teman', data: 'friend' },
					{ value: 'tembok', data: 'wall' },
					{ value: 'tempat tidur', data: 'bed' },
					{ value: 'tempat tinggal', data: 'place to stay' },
					{ value: 'tempat lahir', data: 'place of birth' },					
					{ value: 'tempe', data: 'fermented soybean ' },
					{ value: 'tenggara', data: 'south east' },
					{ value: 'tenggiri', data: 'mackerel' },
					{ value: 'tentu', data: 'sure(ly)' },
					{ value: 'tenun', data: 'woven cloth' },					
					{ value: 'tepi', data: 'edge;side' },
					{ value: 'terang', data: 'clear;bright' },
					{ value: 'teratai', data: 'water lily' },
					{ value: 'terbuat', data: 'made (of)' },
					{ value: 'teri', data: 'small fish' },					
					{ value: 'terima kasih', data: 'thank you' },
					{ value: 'terkejut', data: 'upset' },
					{ value: 'terkenal', data: 'famous' },
					{ value: 'termasuk', data: 'included' },
					{ value: 'terminal', data: 'terminal' },
					{ value: 'tersenyum', data: 'smiling' },
					{ value: 'tertinggal', data: 'to be left' },					
					{ value: 'terong', data: 'eggplant' },
					{ value: 'tetapi', data: 'but' },
					{ value: 'tiang', data: 'pillar' },					
					{ value: 'tiap/setiap', data: 'each' },
					{ value: 'tidur', data: '(to) sleep' },
					{ value: 'tiga', data: 'three' },
					{ value: 'tiga belas', data: 'thirteed' },
					{ value: 'tiga puluh', data: 'thirty' },					
					{ value: 'tiga ratus', data: 'three hundred' },
					{ value: 'tiket', data: 'ticket' },
					{ value: 'timun', data: 'cucumber' },
					{ value: 'timur<', data: 'east' },
					{ value: 'timur laut', data: 'north east' },
					{ value: 'tinggal', data: '(to) stay;(to) live' },
					{ value: 'tinggi', data: 'tall;high' },					
					{ value: 'tipis', data: ' thin' },
					{ value: 'tisu', data: 'tissue' },
					{ value: 'tokek', data: 'gecko' },
					{ value: 'toko grosir', data: 'wholesale shop' },
					{ value: 'toko serba ada (toserba)', data: 'departement store' },
					{ value: 'toko swalayan', data: 'self-service;supermarket' },
					{ value: 'toko', data: 'shop;store' },					
					{ value: 'tolong', data: 'please' },
					{ value: 'tradisional', data: 'traditional' },					
					{ value: 'tropis', data: 'tropical' },
					{ value: 'tua', data: 'old' },
					{ value: 'tuan', data: 'sir' },
					{ value: 'tuh', data: '(sound of express amazement)'},
					{ value: 'Tuhan', data: 'God' },
					{ value: 'tujuan', data: 'intention;goal' },					
					{ value: 'tujuh', data: 'seven' },
					{ value: 'tukang cukur', data: 'barber' },
					{ value: 'tumit', data: 'heel' },
					{ value: 'tunggu', data: '(to) go down' },
					{ value: 'turun', data: 'market' },					
					{ value: 'tutup', data: 'close' },
	
	
				{ value: 'uang kembalian', data: 'change' },
				{ value: 'uang kontan', data: ' cash' },
				{ value: 'uang tunai', data: ' cash money '},
				{ value: 'uang', data: ' money'},
				{ value: 'udang', data: 'shrimp' },					
				{ value: 'udara', data: ' air' },
				{ value: 'ular', data: 'snake' },
				{ value: 'ulos', data: 'traditional batak cloth worn covering shoulder' },					
				{ value: 'umur', data: 'age' },
				{ value: 'ungu', data: 'purple' },					
				{ value: 'unik', data: ' unique' },
				{ value: 'untuk', data: 'for' },
				{ value: 'urus; mengurus', data: '(to) apply (for)'},
				{ value: 'urutan', data: 'order' },
				{ value: 'utara', data: ' north' },
				
				
				
				{ value: 'visa', data: 'visa'},				
				{ value: 'wah', data: '(expression of surprise)' },	
				{ value: 'wajan', data: 'frying pan' },					
				{ value: 'warkop', data: 'coffe shop' },
				{ value: 'warna', data: 'colour(color)' },
				
				{ value: 'warnet', data: 'internet cafe' },
				{ value: 'wartawan', data: 'journalist' },
				{ value: 'warteg', data: 'cheap food stall' },
				{ value: 'wartel', data: 'telephone cafe' },					
				{ value: 'warung', data: 'small shop;roadside stall' },
				{ value: 'wastafel', data: 'sink' },
				{ value: 'wayang kulit', data: 'shadow puppet' },
				{ value: 'wihara', data: 'Buddihst monastery of nunnery' },
				{ value: 'wisata', data: 'tour' },					
				{ value: 'wisawatawan', data: 'tourist' },
				{ value: 'wisma', data: 'guest house' },
				{ value: 'wol', data: 'wool' },
				{ value: 'wortel', data: 'carrot' },
				
				{ value: 'ya', data: 'yes' },
				{ value: 'yang mana', data: 'which one(s)' },					
				{ value: 'yogya (Yogyakarta)', data: 'a town in central java' },
				{ value: 'yunani', data: 'aeroplane(us: airplane)' },

				
					
  ];
  
  // setup autocomplete function pulling from currencies[] array
  $('#autocomplete').autocomplete({
    lookup: currencies,
    onSelect: function (suggestion) {
      var thehtml = '<strong>Indonesian :</strong> ' + suggestion.value + ' <br> <strong>English:</strong> ' + suggestion.data;
      $('#outputcontent').html(thehtml);
    }
  });
  
});